# Base build image
FROM golang:1.12-alpine AS build

# Install git
RUN set -ex; \
    apk update; \
    apk add --no-cache git

# Set workdir
WORKDIR /go/src/gitlab.com/kabestan/repo/baseapp

# Run tests
# CMD CGO_ENABLED=0 go test ./...
# CMD CGO_ENABLED=0 go test -v -run TestCreateUser -count=1 -timeout=5s  ./pkg/web/user_test.go ./pkg/web/base_test.go

# --------------------
# Force the go compiler to use modules
ENV GO111MODULE=on

# Copy project content
RUN echo "Copying resources..."
COPY . .
RUN echo "Copied."

# Compile the project
ENV CGO_ENABLED=0 GOOS=linux
RUN echo "Compiling..."
RUN go test -mod=vendor -o /go/bin/web.test -c pkg/web/user_test.go pkg/web/base_test.go
RUN echo "Compile output in: base.test"

# Coying only the results without the artifacts to fresh Alpine image.
FROM alpine
WORKDIR /srv
COPY --from=build /go/bin/web.test ./web.test

# Entrypoint
ENTRYPOINT ./web.test
