# Tests

test-selected:
	clear
	#make -f makefile.test test-mock
	#@make spacer
	make -f makefile.test test-auth-create-user

## Mock
test-mock:
	go test -v -run TestMock -count=1 -timeout=5s  ./pkg/auth/service/user_test.go

## User
test-auth-create-user:
	go test -v -run TestCreateUser -count=1 -timeout=5s  pkg/web/user_test.go pkg/web/base_test.go pkg/web/pkged.go
